export default {
  frontend: {
    followers: '/followers',
    following: '/following',
    homePage: '/home',
    root: '/',
    signIn: '/login',
    signUp: '/register',
    userPage: '/user',
  },
  backend: {
    frontPage: '/front_page',
    frontPageFollowing: '/front_page_following',
    logOut: '/sign_out',
    sessions: '/sessions',
    signIn: '/sign_in',
    signUp: '/sign_up',
    comments: '/comments',
    commentLikes: '/comment_likes',
    commentReposts: '/comment_reposts',
    posts: '/posts',
    postLikes: '/post_likes',
    postReposts: '/post_reposts',
  },
};
